import {
    NUTRITION_TYPE_ROUTE,
    REGISTER_ACCOUNT_ROUTE,
    REGISTER_ACTIVITY_LEVEL_ROUTE,
    REGISTER_ACTIVITY_PER_WEEK_ROUTE,
    REGISTER_ALLERGENIC_ROUTE,
    REGISTER_CALCULATION_TYPE_ROUTE,
    REGISTER_CALORIE_RESTRICTION_ROUTE,
    REGISTER_GOAL_ROUTE,
    REGISTER_NUTRITION_INTRO_ROUTE,
    REGISTER_PAL_ROUTE,
    REGISTER_PERSONAL_ROUTE,
} from '../../routes.ts';

export const REGISTER_STEP = {
    PERSONAL: { sequence: 1, route: REGISTER_PERSONAL_ROUTE },
    GOAL: { sequence: 2, route: REGISTER_GOAL_ROUTE },

    NUTRITION_INTRO: { sequence: 3, route: REGISTER_NUTRITION_INTRO_ROUTE },
    ACTIVITY_LEVEL: { sequence: 3, route: REGISTER_ACTIVITY_LEVEL_ROUTE },
    ACTIVITY_PER_WEEK: { sequence: 3, route: REGISTER_ACTIVITY_PER_WEEK_ROUTE },
    PAL: { sequence: 3, route: REGISTER_PAL_ROUTE },
    NUTRITION_TYPE: { sequence: 3, route: NUTRITION_TYPE_ROUTE },
    CALCULATION_TYPE: { sequence: 3, route: REGISTER_CALCULATION_TYPE_ROUTE },
    CALORIE_RESTRICTION: { sequence: 3, route: REGISTER_CALORIE_RESTRICTION_ROUTE },

    ALLERGENIC: { sequence: 4, route: REGISTER_ALLERGENIC_ROUTE },
    ACCOUNT: { sequence: 5, route: REGISTER_ACCOUNT_ROUTE },
}